Use federatedCloudId instead of email for user identification between servers
cs3org/OCM-API pull request #102
Opened 2024-08-31 18:54 UTC by MahdiBaghbani

This PR changes 2 things:

1. Renames `userID` to `userId` to be consistent with `camelCase` across the whole specification eg. `providerId`
2. Adds a field to the `invite-flow` called `federatedCloudId`.

---

**Reason behind the new field**
Previously OCM used email as a way to identify remote users. 

This is essential when a party tries to send a `share` or `notification` to another party because it is going to find the domain name of the recipient from their id (which currently is set to email, look at `Reva` and `ScienceMesh`)

This becomes problematic when the user's email name or domain is different than the user's username or provider domain. for example:

1. Alice is on provider `apollo.space` with username `alice1998` and has email `alice1998@apollo.space` -> OK
2. Bob is on provider `nasa.space` with username `bob` and has email `bob@gmail.com` -> Problem

Vendors can overcome this problem by not providing the user's email and just returning username@provider-domain in the email field.

I think it is a good idea to make a distinction between email and `cloudId`.

2024-09-03 07:23 UTC, glpatcern approved these changes
This is an interesting proposal as the net sum is to add the `username` of a remote user as known by the remote EFSS, on top of the `email` identifier that indeed may not be related to the remote EFSS' domain.

I think some comment from @labkode as originally involved in the conception, as well as @michielbdejong, is more than welcome prior to merging this enhancement.

2024-09-03 09:24 UTC, michielbdejong commented on spec.yaml
> +            description: Federated cloud ID of the user accepting the invite. it should be in the form of username@provider-domain.
I'm confused by this, what is the difference between username `username` and the userId `51dc30ddc473d43a6011e9ebba6ca770` in this context?

Is this invite being accepted by `richard@receiver.org` or by `51dc30ddc473d43a6011e9ebba6ca770@receiver.org`?

2024-09-03 09:26 UTC, michielbdejong requested changes
Let's not merge this until we understand the relationship between the proposed `federatedCloudId` and the existing `userId`

2024-09-04 07:32 UTC, MahdiBaghbani commented
It seems, that the invite is being accepted by `51dc30ddc473d43a6011e9ebba6ca770@receiver.org`

As implemented in [ScienceMesh](https://github.com/sciencemesh/nc-sciencemesh/blob/66b8562a4676f22a8ef102eba732c1852f3a6065/lib/RevaHttpClient.php#L108-L142)

So no need for the new filed in this PR.

2024-09-04 07:33 UTC, MahdiBaghbani commented on spec.yaml
> +            description: Federated cloud ID of the user accepting the invite. it should be in the form of username@provider-domain.
It was accepted by `51dc30ddc473d43a6011e9ebba6ca770@receiver.org`.

2024-09-04 07:36 UTC, MahdiBaghbani commented
I think this `https://` (look at [Test Suite](https://github.com/pondersource/dev-stock/issues/128)) bug is originated from here.

the `"recipientProvider": "https://receiver.org/"` has the protocol schema instead of just the domain.

2024-09-04 07:49 UTC, michielbdejong commented
> Proposal:
Merge both `userId` and `recipientProvider` into `cloudId` = `userId@recipientProviderDomain`

That would be a breaking spec change with costs to implementers. What if instead we just improve how the existing `userId` and `recipientProvider` fields are documented? In particular, make it clear that `recipientProvider` should be an FQDN and not a URL?

2024-09-04 07:54 UTC, MahdiBaghbani commented
Right that makes sense since it is already inside Reva and ScienceMesh, and they both don't check if it is URL or FQDN

2024-09-04 09:43 UTC, michielbdejong commented
So do we want to close this PR without merging then?

2024-09-04 09:54 UTC, MahdiBaghbani commented
Yes!

> we just improve how the existing userId and recipientProvider fields are documented.

that would be in another PR.

2024-09-04 11:33 UTC, closed without merging