Use pseudo-code for the signature creation and verification examples
cs3org/OCM-API pull request #129
Opened 2024-09-09 10:21 UTC by glpatcern

This is in response to my own remark that pseudo-code is more appropriate in specs. I hope I got the process right!

2024-09-09 10:28 UTC, MahdiBaghbani approved these changes
It is more general than the PHP (looks like Python now 😄) 
LGTM

2024-09-09 14:13 UTC, mickenordin approved these changes

2024-09-10 06:38 UTC, glpatcern commented
> It is more general than the PHP (looks like Python now 😄) LGTM

Surely I got inspired by Python :-D but hopefully the readability got improved

2024-09-10 07:29 UTC, glpatcern reviewed
I edited again the example, @michielbdejong a final pass?

2024-09-10 07:29 UTC, glpatcern commented on README.md
> +    'keyId': 'https://sender.org/ocm',  # The sending server's keyId as advertised at the discovery endpoint
Reviewing myself, I modified this to clarify that the keyId is per sending server (and not per user)

2024-09-12 07:43 UTC, michielbdejong commented on README.md
> +    'host': 'recipient-hostname',
```suggestion
    'host': 'recipient-fqdn',
```

2024-09-12 07:46 UTC, michielbdejong commented on README.md
> +    'keyId': 'https://sender.org/ocm',  # The sending server's keyId as advertised at the discovery endpoint
```suggestion
    'keyId': 'sender-fqdn',  # The sending server's FQDN; you can find its public key through OCM API discovery
```

2024-09-12 07:47 UTC, michielbdejong commented on README.md
> +    'host': localhost(),
```suggestion
    'host': 'example.com',
```

2024-09-12 07:48 UTC, michielbdejong requested changes
Great stuff - only remark, let's use FQDNs here too instead of URLs, for consistency.

2024-09-12 08:21 UTC, glpatcern commented
> Great stuff - only remark, let's use FQDNs here too instead of URLs, for consistency.

Good point, just committed your suggestions (and a trivial variant). Good to go?

2024-09-12 13:36 UTC, michielbdejong approved these changes

2024-09-12 14:06 UTC, merged